### ISSUE TITLE
some methods and callbacks dont work

### ISSUE THREAD

**Issue by meeeeeepo** [sdkbox/sdkbox-sample-appodeal#4]
1. onBannerPresent callback don’t call on iOS 
2. skippableVideo callbacks are not working at all
3. disableNetworkForAdType doesn’t work

**Comment by darkdukey** [comment]
Just updated the sample all 3 issues should be fixed.

**Comment by meeeeeepo** [comment]
hey, i tested updated plugin, disableNetworkForAdType still doesn't work but all other issues were fixed

**Comment by hugohuang1111** [comment]
@meeeeeepo disableNetworkForAdType doesn't work on android or ios or both?

**Comment by meeeeeepo** [comment]
@hugohuang1111 I tested ios version only

**Comment by hugohuang1111** [comment]
i check disableNetworkForAdType function code, it's ok.
can you give me a detail test step, so i can reproduce
